### ISSUE TITLE
Unable to reproduce projected files using 'project-aligned-trees.py'

### ISSUE THREAD

**Issue by jbrry** [ftyers/cross-lingual-parsing#4]
Hi there!

I am trying to follow the steps in this repository. I am running `project-aligned-trees.py` with the recommended input settings: `python3 project-aligned-trees.py <conllu output> <alignments> <parallel text>`

Using Danish as an example:

```python utils/project-aligned-trees.py data/faroese/fao_wiki.apertium.fao-dan.udpipe.parsed.conllu data/faroese/fao_wiki.apertium.fao-dan.align.txt data/faroese/fao_wiki.apertium.dan-fao.input.txt > data/faroese/dan-fao.projected-attempt.conllu```

The output is different to the projected files which are released in the repository.

```
head -27 data/faroese/dan-fao.projected-attempt.conllu 
# newdoc
# newpar
# sent_id = 1
# text = ﻿Føroyar liggja í Norðuratlantshavi , 280 km norðan fyri Hetland , 430 km frá Íslandi og 575 km vestan fyri Noreg .
1       ﻿Føroyar _       NOUN    _       _       2       nsubj   _       _
2       liggja  _       VERB    _       _       0       root    _       _
3       í       _       ADP     _       _       4       case    _       _
4       Norðuratlantshavi       _       PROPN   _       _       7       nmod    _       SpaceAfter=No
5       ,       _       PUNCT   _       _       4       punct   _       _
6       280     _       NUM     _       _       7       nummod  _       _
7       km      _       NOUN    _       _       2       obj     _       _
9       fyri    _       ADV     _       _       10      advmod  _       _
10      Hetland _       ADV     _       _       12      advmod  _       _
11      ,       _       ADP     _       _       12      case    _       _
12      430     _       PROPN   _       _       20      nmod    _       SpaceAfter=No
13      km      _       PUNCT   _       _       12      punct   _       _
14      frá     _       NUM     _       _       15      nummod  _       _
15      Íslandi _       NOUN    _       _       20      nmod    _       _
16      og      _       ADP     _       _       17      case    _       _
17      575     _       PROPN   _       _       20      nmod    _       _
18      km      _       CCONJ   _       _       20      cc      _       _
19      vestan  _       NUM     _       _       20      nummod  _       _
20      fyri    _       NOUN    _       _       21      conj    _       _
21      Noreg   _       ADV     _       _       2       advmod  _       _
22      .       _       ADP     _       _       23      case    _       _

```

The original file:

```
head -27 data/faroese/fao_wiki.apertium.dan-fao.udpipe.projected.conllu
# newdoc
# newpar
# sent_id = 1
# text = ﻿Føroyar liggja í Norðuratlantshavi , 280 km norðan fyri Hetland , 430 km frá Íslandi og 575 km vestan fyri Noreg .
1       ﻿Føroyar _       NOUN    _       _       2       nsubj   _       _
2       liggja  _       VERB    _       _       0       root    _       _
3       í       _       ADP     _       _       4       case    _       _
4       Norðuratlantshavi       _       PROPN   _       _       7       nmod    _       SpaceAfter=No
5       ,       _       PUNCT   _       _       4       punct   _       _
6       280     _       NUM     _       _       7       nummod  _       _
7       km      _       NOUN    _       _       2       obj     _       _
8       norðan  _       ADV     _       _       10      advmod  _       _
9       fyri    _       ADV     _       _       11      advmod  _       _
10      fyri    _       ADP     _       _       11      case    _       _
11      Hetland _       PROPN   _       _       19      nmod    _       SpaceAfter=No
12      ,       _       PUNCT   _       _       11      punct   _       _
13      430     _       NUM     _       _       14      nummod  _       _
14      km      _       NOUN    _       _       19      nmod    _       _
15      frá     _       ADP     _       _       16      case    _       _
16      Íslandi _       PROPN   _       _       19      nmod    _       _
17      og      _       CCONJ   _       _       19      cc      _       _
18      575     _       NUM     _       _       19      nummod  _       _
19      km      _       NOUN    _       _       20      conj    _       _
20      vestan  _       ADV     _       _       2       advmod  _       _
21      fyri    _       ADP     _       _       22      case    _       _
22      Noreg   _       PROPN   _       _       20      obl     _       SpaceAfter=No
23      .       .       PUNCT   _       _       2       punct   _       SpacesAfter=\r\n
```

Additionally, the output I get has head IDs which are out-of-range, e.g. token 22's head is 23 which is not in the sentence and this causes the parser to break.

I'm just wondering what would be the appropriate steps to reproduce the files as they are in the directory as I might be missing something, thanks!

My environment: `Python 3.6.0 :: Anaconda 4.3.1 (64-bit)
`

**Comment by ftyers** [comment]
@Jbar-ry I think what we did for the experiments was just to throw away trees that are broken before training. Is that right @maryszmary and @melanoya ? 

Note that in the original files there is *fyri* twice. In general if the number of tokens isn't the same in the output I think we threw away the trees. This is just an implementation error.

**Comment by jbrry** [comment]
Hi Fran, thanks for that. It's good to know that this is the case as I wasn't sure if I was doing something incorrectly. In the meantime, I should be able to track the inputs and outputs of the various files to see the what scripts are involved in the filtering etc. 

From what I've noticed, it tends to happen in cases where there is a longer source sentence, and thus a source token's head may be outside the range of the target sentence. The function `check_align` makes sure that there is at least a 1:1 mapping to all source indices in the alignment dictionary, which can result in target keys which are outside the range of the target sentence.

In the paper, it mentions (for Danish) that 28,632 sentences were included (out of 28,862), which means that only around 230 sentences are discarded which is an almost negligible amount in this case!

**Comment by jbrry** [comment]
I was able to train and evaluate all models for the mono-treebank projection experiments after using `validate_treebank.py` on the outputs of `project-aligned-trees.py`. I will close the issue now, thanks!

**Comment by ftyers** [comment]
@Jbar-ry great! Thanks :)
